version: '3.8'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    image: localstack/localstack:0.12.7
    ports:
      - "4566:4566"
    environment:
      - SERVICES=${SERVICES-s3}
      - START_WEB=0
      - INIT_SCRIPTS_PATH=${INIT_SCRIPTS_PATH-/docker-entrypoint-initaws.d}
    volumes:
      - ./aws:/docker-entrypoint-initaws.d