version: '3.8'

networks:
  local:

services:
  grafana:
    container_name: "grafana"
    image: grafana/grafana:7.5.5
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./influxdb.yml:/etc/grafana/provisioning/datasources/influxdb.yml
    #  - ./dashboard.json:/etc/grafana/provisioning/datasources/dashboards.json
    networks:
      - local
    depends_on:
      - influxdb
  influxdb:
    container_name: "influxdb"
    image: influxdb:1.8.5-alpine
    ports:
      - "8083:8083"
      - "8086:8086"
      - "2003:2003"
    environment:
      - INFLUXDB_DB=influxdb
    networks:
      - local